theme: jekyll-theme-hacker
title: Welcome to New Horizons homepage!
description: Eric Clancy ePortfolio covering Software Engineering and Design, Algorithms and Data Structure, Databases and Professional Self-Assessment
